--Ex03
--New Table with ex02
USE esakraw;
CREATE EXTERNAL TABLE USERRECORD_COPY 
LIKE esakraw.USERRECORDEXT;
--LOADING DATA 
INSERT OVERWRITE  TABLE esakraw.USERRECORD_COPY
SELECT * FROM esakraw.USERRECORDEXT;
