USE esakraw;
DROP TABLE IF EXISTS USER_SKEW;
CREATE EXTERNAL TABLE esakraw.USER_SKEW(
FirstName STRING ,
LastName STRING,
CompanyName STRING,
Address STRING,
City STRING , 
State STRING ,
Post BIGINT,
Phone ARRAY<STRING>,
Email MAP<STRING,STRING> ,
WebUrl STRING
)
COMMENT 'FIRST EXTERNAL SKEWED TABLE'
SKEWED BY (COUNTRY) ON ('AU')
STORED AS AVRO;
--Loading Data Into Table
INSERT OVERWRITE  TABLE esakraw.USER_SKEW SELECT * FROM esakraw.USERRECORDEXT;
