USE ${HIVECONF.TRG_DATABASENAME};
CREATE TABLE IF NOT EXISTS ${HIVECONF.TRG_DATABASENAME}.ex07copy 
ROW FORMAT SERDE "org.apache.hadoop.hive.serde2.columnar.ColumnarSerDe"
STORED AS RCFILE
AS
SELECT * FROM esakraw.ex07;
